server:
  port: 8909

spring:
  application:
    name: sp-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/mydatabase
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    generate-ddl: true
    hibernate:
      ddl-auto: update




